name: workflow overview

on:
  workflow_dispatch:


jobs:
 a_simple_job:
    name: my simple job name
    runs-on: unbuntu-latest
    steps:
      - name: name of my step
        id: stepId
        run: echo "this is the first setup from the first job"
      - name: another step
        id: shellstep
        shell: python
        run: print("this step is using the python shell")
       
 
